# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iArch-U
# email: iarch@posl.ait.kyushu-u.ac.jp
description: >
  iArch-U is an Eclipse plug-in for managing and modelling uncertainty which arises during the software development process.
baseurl: "/iArch" # the subpath of your site, e.g. /blog
url: "http://posl.github.io" # the base hostname & protocol for your site
github_username:  posl

# Build settings
markdown: kramdown
exclude: [vendor]
repository: posl/posl.github.io
highlighter: rouge
